### ISSUE TITLE
Docs TODO

### ISSUE THREAD

**Issue by mmgoodnow** [cross-seed/cross-seed#283]
- [ ] fix broken links
- [x] Architecture
- [x] duplicate categories option
- [ ] rss command
- [ ] no port
- [ ] verbose option
- [ ] remove references to /cross-seeds folder
- [ ] transmission
